<?php

/**
 * @file
 */

// Load source type.
function brdg_core_get_source_with_name($name) {
	$vocabulary_name = 'data_source';
    $vocabulary = taxonomy_vocabulary_machine_name_load($vocabulary_name);
    $query = new EntityFieldQuery;
    $query->entityCondition('entity_type', 'taxonomy_term')
    	->propertyCondition('vid', $vocabulary->vid)
    	->propertyCondition('name', $name, 'LIKE');
    $result = $query->execute();

    if ($result) {
    	$term = array_shift($result['taxonomy_term']);
    	return taxonomy_term_load($term->tid);
    }
    return NULL;
}

// Logger function
function brdg_core_log_cron($source_type, $query_ret) {
	//TODO
}

function brdg_insert_node($temp_node) {

}

// Remove non utf8 code from string.
function remove_non_utf8_string($string) {
  $string = preg_replace('/'.
   '[\x00-\x08\x10\x0B\x0C\x0E-\x19\x7F]'.
   '|[\x00-\x7F][\x80-\xBF]+'.
   '|([\xC0\xC1]|[\xF0-\xFF])[\x80-\xBF]*'.
   '|[\xC2-\xDF]((?![\x80-\xBF])|[\x80-\xBF]{2,})'.
   '|[\xE0-\xEF](([\x80-\xBF](?![\x80-\xBF]))|'.
   '(?![\x80-\xBF]{2})|[\x80-\xBF]{3,})'.
   '/S',
   '?', $string);
   
  //reject overly long 3 byte sequences
  //and UTF-16 surrogates and replace with ?
  $string = preg_replace('/'.
   '\xE0[\x80-\x9F][\x80-\xBF]'.
   '|\xED[\xA0-\xBF][\x80-\xBF]'.
   '/S',
   '?', $string);

  return $string;
}

// Save image from URL.
function add_image_from_url($image_url, $location = 'third_content') {
  $directory = file_build_uri($location);
  if (!file_prepare_directory($directory, FILE_CREATE_DIRECTORY)) {
    $directory = NULL;
  }
  if (function_exists('brdg_soundcloud_save_url_file')) {
    $file = brdg_soundcloud_save_url_file($image_url, $directory, TRUE);
  }
  else {
    $file = system_retrieve_file($image_url, $directory, TRUE, FILE_EXISTS_REPLACE);
  }
  return $file;
}

// Check weather post is insert into our system
function brdg_core_media_is_inserted($id) {
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'node')
  ->entityCondition('bundle', 'content_from_source')
  ->fieldCondition('field_source_id', 'value', $id)
  ->execute();
  return !!$result;
}

// Alter node that been inserted system.
function brdg_core_node_save($node, $from, $entity = NULL) {
    $source_id = $node->field_source_id[LANGUAGE_NONE][0]['value'];
    if ($source_id && brdg_core_media_is_inserted($source_id)) {
        return FALSE;
    } 
    $modules = module_list();
    $filters = array();
    foreach ($modules as $module) {
        $func = $module.'_brdg_core_filter';
        if (function_exists($func) && $func($node, $from, $entity) === FALSE) {
            //return;
        }
    }
    node_save($node);
}

/**
 * Implements hook_services_view_alter()
 */
function brdg_core_services_view_alter(&$output, $views) {
  foreach ($output as &$output_item) {
    if (isset($output_item->field_user_profile_image) && !empty($output_item->field_user_profile_image)) {
      $output_item->field_user_profile_image = file_create_url($output_item->field_user_profile_image['uri']);
    }
    if (isset($output_item->field_media_image) && !empty($output_item->field_media_image)) {
      $html = array_shift($output_item->field_media_image);
      preg_match( '@src="([^"]+)"@' , $html , $match);
      $output_item->field_media_image = $match[1];
    }
  }
}

/**
 * Implements hook_init()
 */
function brdg_core_init() {
    drupal_add_js(drupal_get_path('module', 'brdg_core').'/js.example.js');
}

function brdg_core_is_youku_link($url) {
  if (strpos($url, 'youku.com') !== FALSE) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_comment_insert()
 * The comment is unpublish as default
 */
function brdg_core_comment_insert($comment) {
  $comment->status = 0;
  comment_save($comment);
}

// Helper function to load drupal user from twitter screen name
function brdg_core_load_drupal_user_with_screen_name($screen_name, $source_type) {
  $allowed_third_type = array('twitter', 'weibo', 'instagram');
  if (!in_array($source_type, $allowed_third_type)) {
    return;
  }
///////////// would be deleted later
  // // First check screen name in DB
  // $query = db_select("twitter", 't')
  //  ->fields('t', array('twitter_id'))
  //  ->condition('t.screen_name', $screen_name);
  // $twitter_id = $query->execute()->fetchCol();

  // // If user not already in twitter table,
  // // Then we fetch it from twitter site and add it into our system
  // if (!$twitter_id) {
  //  $api = brdg_twitter_connect();
  //  try {
  //    $twitter_account = $api->users_show($screen_name);
  //  } catch (TwitterException $e) {
  //    form_set_error('screen_name', t('Request failed: @message.', array('@message' => $e->getMessage())));
  //    return;
  //  }
  //  // Save the new Twitter account and set the user's uid who added it.
  //  // global $user;
  //  // $twitter_account->uid = $user->uid;
  //  twitter_account_save($twitter_account, TRUE);
  // }
//////////////////////////////////////////////////////
  $query = new EntityFieldQuery();
  if ($source_type == 'twitter') {
    $field = 'field_twitter_screen_name';
  }
  elseif ($source_type == 'instagram') {
    $field = 'field_instagram_screen_name';
  }
  elseif ($source_type == 'weibo') {
    $field = 'field_weibo_screen_name';
  }
  $ret = $query->entityCondition('entity_type', 'user')
    ->fieldCondition($field, 'value', $screen_name)
    ->execute();
  if (!isset($ret['user'])) {
    return;
  }
  $uid = array_shift($ret['user']);
  return user_load($uid->uid);
}

/**
 * Act on a flagging.
 *
 * @param $op
 *  The operation being performed: one of 'flag' or 'unflag'.
 * @param $flag
 *  The flag object.
 * @param $content_id
 *  The id of the content (aka entity) the flag is on.
 * @param $account
 *  The user account performing the action.
 * @param $fcid
 *  The id of the flagging in the {flag_content} table.
 */
function brdg_core_flag($op, $flag, $content_id, $account, $fcid) {
  if ($op =='flag' && $account->uid == 0) {
    $node = $flag->_load_content($content_id);
    if ($flag->content_type == 'node') {
      $node->field_anonymous_flaged[LANGUAGE_NONE][0]['value'] += 1;
      node_save($node);
    }
  }
  elseif ($op == 'unflag' && $account->uid == 0) {
    $node = $flag->_load_content($content_id);
    if ($flag->content_type == 'node') {
      $node->field_anonymous_flaged[LANGUAGE_NONE][0]['value'] < 1 ? 
      "":   $node->field_anonymous_flaged[LANGUAGE_NONE][0]['value'] -= 1;
      node_save($node);
    }
  }
}

