<?php

/**
 * @file
 */

// Load source type.
function brdg_core_get_source_with_name($name) {
	$vocabulary_name = 'data_source';
    $vocabulary = taxonomy_vocabulary_machine_name_load($vocabulary_name);
    $query = new EntityFieldQuery;
    $query->entityCondition('entity_type', 'taxonomy_term')
    	->propertyCondition('vid', $vocabulary->vid)
    	->propertyCondition('name', $name, 'LIKE');
    $result = $query->execute();

    if ($result) {
    	$term = array_shift($result['taxonomy_term']);
    	return taxonomy_term_load($term->tid);
    }
    return NULL;
}

// Logger function
function brdg_core_log_cron($source_type, $query_ret) {
	//TODO
}

function brdg_insert_node($temp_node) {

}

// Remove non utf8 code from string.
function remove_non_utf8_string($string) {
  $string = preg_replace('/'.
   '[\x00-\x08\x10\x0B\x0C\x0E-\x19\x7F]'.
   '|[\x00-\x7F][\x80-\xBF]+'.
   '|([\xC0\xC1]|[\xF0-\xFF])[\x80-\xBF]*'.
   '|[\xC2-\xDF]((?![\x80-\xBF])|[\x80-\xBF]{2,})'.
   '|[\xE0-\xEF](([\x80-\xBF](?![\x80-\xBF]))|'.
   '(?![\x80-\xBF]{2})|[\x80-\xBF]{3,})'.
   '/S',
   '?', $string);
   
  //reject overly long 3 byte sequences
  //and UTF-16 surrogates and replace with ?
  $string = preg_replace('/'.
   '\xE0[\x80-\x9F][\x80-\xBF]'.
   '|\xED[\xA0-\xBF][\x80-\xBF]'.
   '/S',
   '?', $string);

  return $string;
}

// Save image from URL.
function add_image_from_url($image_url, $location = 'third_content') {
  $directory = file_build_uri($location);
  if (!file_prepare_directory($directory, FILE_CREATE_DIRECTORY)) {
    $directory = NULL;
  }
  if (function_exists('brdg_soundcloud_save_url_file')) {
    $file = brdg_soundcloud_save_url_file($image_url, $directory, TRUE);
  }
  else {
    $file = system_retrieve_file($image_url, $directory, TRUE);
  }
  return $file;
}

// Check weather post is insert into our system
function brdg_core_media_is_inserted($id) {
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'node')
  ->entityCondition('bundle', 'content_from_source')
  ->fieldCondition('field_source_id', 'value', $id)
  ->execute();
  return !!$result;
}

/**
 * Implements hook_views_query_alter()
 */
function brdg_core_views_query_alter(&$view, &$query) {
    if ($view->name == 'pictures') {
        //dpm($query);
    }
}

